

---
dependency:
  name: gilt





# delegate example: https://github.com/freedomofpress/securedrop/blob/30257872db2ccad24141ff24269ff2f959a519fd/molecule/builder/create.yml
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'docker exec --user vagrant --tty -ti {instance} env TERM=xterm bash'
    ansible_connection_options:
      ansible_connection: docker


lint:
  name: yamllint
  enabled: False

platforms:
  # source: https://blog.opsfactory.rocks/testing-ansible-roles-with-molecule-97ceca46736a
  # source: https://github.com/solita/docker-systemd
  # source: https://github.com/solita/docker-systemd-ssh/blob/master/Dockerfile
  - name: boss-ansible-role-rbenv-xenial



provisioner:
  name: ansible
  playbooks:
    prepare: ''
    create: ''
  options:
    vvv: True

  lint:
    name: ansible-lint
    enabled: False
    # EANSIBLE0013 should not be raised for shell tasks that use globs.
    options:
      x: ANSIBLE0013

verifier:
  name: testinfra
  options:
    verbose: True
  lint:
    name: flake8
    enabled: False


scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - create
    - converge
    - verify
    - destroy



