---
- name: Converge
  hosts: all
  become: yes
  become_method: sudo
  environment:
    SHELL: /bin/bash
    TERM: xterm
  roles:
    - role: boss-ansible-role-core
    - role: boss-ansible-role-fact
    - role: boss-ansible-role-environment
    - role: boss-ansible-role-users
      boss__users_users:
      - username: vagrant
        groups: ['sudo', 'adm', 'vagrant']
        append: yes
        uid: 1000
        gid: 1000
        home: /home/vagrant

    - role: boss-ansible-role-rbenv
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__rbenv_default_gems_file: "/home/{{ bossjones__user }}/.dotfiles/ruby/default-gems"
      boss__rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev
      - ctags
      boss__rbenv:
        env: user
        version: v1.1.1
        default_ruby: 2.4.2
        rubies:
        - version: 2.4.2
      boss__rbenv_users:
      - "{{ bossjones__user }}"
      boss__rbenv_repo: "https://github.com/rbenv/rbenv.git"
      boss__rbenv_plugins:
        - { name: "rbenv-vars",         repo: "https://github.com/rbenv/rbenv-vars.git",         version: "master" }
        - { name: "ruby-build",         repo: "https://github.com/rbenv/ruby-build.git",         version: "master" }
        - { name: "rbenv-default-gems", repo: "https://github.com/rbenv/rbenv-default-gems.git", version: "master" }
        - { name: "rbenv-installer",    repo: "https://github.com/rbenv/rbenv-installer.git",    version: "master" }
        - { name: "rbenv-update",       repo: "https://github.com/rkh/rbenv-update.git",         version: "master" }
        - { name: "rbenv-whatis",       repo: "https://github.com/rkh/rbenv-whatis.git",         version: "master" }
        - { name: "rbenv-use",          repo: "https://github.com/rkh/rbenv-use.git",            version: "master" }
        - { name: "rbenv-ctags",        repo: "https://github.com/tpope/rbenv-ctags.git",        version: "master" }
        - { name: "rbenv-each",         repo: "https://github.com/rbenv/rbenv-each.git",         version: "master" }
        - { name: "rbenv-aliases",      repo: "https://github.com/tpope/rbenv-aliases.git",      version: "master" }

      boss__rbenv_root: "{% if boss__rbenv.env == 'system' %}/usr/local/rbenv{% else %}~/.rbenv{% endif %}"


